### ISSUE TITLE
Add ability to update visualizations

### ISSUE THREAD

**Issue by rob-h-m** [SmartColumbusOS/discovery_ui#12]
@carriebrinkley commented on [Tue Aug 27 2019](https://github.com/smartcitiesdata/discovery_ui/issues/181)

### Business Value: 

This is a first slice of creating the ability for users to save/share queries for future use. The ultimate goal is to provide efficiencies for the end user so that coming to the platform will be a time-save for all of their data needs. 

### Acceptance Criteria: 

- [x] Each time the user clicks the "save" button...
- [x] They are presented with a dialog box to name the query
- [x] The query is associated with the user's Auth0 subject ID
- [x] Uniqueness is not enforced based on the name of the saved query
- [x] @jakeclark has signed off on the UX 

#### Tech note:
- Play after retrieval card #8 

### Amigos: 

@jakeclark

**Comment by bbrewer-papa-x** [comment]
Need to make a card to address sharing and public access to saved visualizations
