### ISSUE TITLE
Joomla CMS Page CSS Refactoring for mobile and tablet viewports

### ISSUE THREAD

**Issue by jakeclark** [SmartColumbusOS/discovery_ui#131]
As a user, I want a consistent experience across the Joomla site, so that I may easily browse and consume information. 

A/C:

- [x] Audit all CMS pages in desktop, tablet, and mobile views - headers and content should not break when resizing

- [x] Audit Sheet: https://docs.google.com/spreadsheets/d/1_LXVW1rfd_TKbfbsAG3YL7lFBTnRkQ0gkTVyp2IO2k8/edit#gid=0

- [x] If broken, fix in-page CSS for header images and other content. Document fix in spreadsheet

Good:

![image.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/c303a50b-08c7-45ef-af62-5bb24c366f19)

Bad: 
![image.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/a34b356e-fa51-472b-b5c0-a81b3f35317f)

![image.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/8b1fad3d-aeec-48de-b63c-774f59e7d3e6)

**Comment by dunson062786** [comment]
Do we care about tableau components fitting on mobile?

**Comment by dunson062786** [comment]
There is nothing on https://www.smartcolumbusos.com/data-stories/events. Should we delete it?

**Comment by dunson062786** [comment]
Are you sure it's fine to have the double images in the header?
