### ISSUE TITLE
Associate an Account from Auth0 with an Organization

### ISSUE THREAD

**Issue by rob-h-m** [SmartColumbusOS/discovery_ui#14]
_As Connor
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future_

#### Acceptance Criteria:
- [ ] Be able to store an Organization association with the account
- [ ] ~~If logged in with an account tied to an organization, their restricted datasets are available~~

#### Technical Notes:

- Discovery API's database should persist the relationship between organization and user in a cross-reference table when it receives an `user:organization:associate` event

#### Business Value:
1.) Lays the foundation for improved user experience in the OS through personalization
2.) Continued separation between public and restricted datasets
3.) Risk reduction by implementing through external account management services such as Google

#### Amigos:
@carriebrinkley , @JarredOlson 

@rob-h-m commented on Sep 09: this was [discovery_ui #204](https://github.com/smartcitiesdata/discovery_ui/issues/204)

**Comment by abrock-accenture** [comment]
Blocking this card on discovery_api #257
