### ISSUE TITLE
Discovery UI Uses Auth0 for All Authentication

### ISSUE THREAD

**Issue by rob-h-m** [SmartColumbusOS/discovery_ui#17]
@rob-h-m commented on [Mon Sep 09 2019](https://github.com/smartcitiesdata/discovery_ui/issues/207)

#### User Story:

As Connor
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future

#### Acceptance Criteria:
- [ ] Discontinue using LDAP in the Discovery UI
- [ ] Change the Login button to use Auth0 instead of LDAP

#### Tech Notes:
- Update all existing 'secured' API calls to use the `AuthenticatedHTTPClient` that is already used to call the visualization APIs
- Upon successful login, user should be returned to the URL they were at when they clicked login, including query parameters. This should be handled by discovery_ui#20, but won't really be fully testable until we play this card.
  - As of 11/26/2019, discovery_ui#20 is not complete yet.  For now, we will redirect the user back to the root of the site after a successful login.

#### Business Value:
1.) Lays the foundation for improved user experience in the OS through personalization
2.) Continued separation between public and restricted datasets
3.) Risk reduction by implementing through external account management services such as Google

#### Amigos:
@carriebrinkley , @JarredOlson, @mcsearchin

**Comment by mcsearchin** [comment]
Depends on smartcitiesdata/discovery_api#283 and probably also smartcitiesdata/discovery_ui#20

**Comment by mcsearchin** [comment]
@carriebrinkley @rob-h-m We will likely need to re-point this card.

**Comment by mcsearchin** [comment]
TODO:
[ ] Replace Login button with one that goes to Auth0
[ ] use `AuthenticatedHTTPClient` everywhere that we call our app
[ ] update `/oauth` path to redirect back to root
