### ISSUE TITLE
Provide users with the ability to reference their saved queries

### ISSUE THREAD

**Issue by carriebrinkley** [SmartColumbusOS/discovery_ui#26]
@carriebrinkley commented on [Tue Oct 01 2019](https://github.com/SmartColumbusOS/scosopedia/issues/101)

This is the thinnest slice of the notion of a user profile.  

#### Acceptance Criteria

- [x] As a user, when I am logged in, I am able to view a list of the queries that I have saved 
- [x] As a user, when I am logged in and click on a previously saved query, I am taken to the visualization page associated with that query 
- [x] As a user, when I am logged in and make updates to a previously saved query, then the query is updated 
- [x] As a user, when I log out of the OS through Auth0, I am no longer able to see my saved queries
- [ ] @jakeclark has signed off on all UX

#### Tech Notes

- This work ties together the ability to save/fetch queries and user authorization through Auth0
- This will route to a dataset-less visualization page

#### Amigos

@jakeclark , @carriebrinkley , @bbrewer-papa-x

**Comment by jakeclark** [comment]
PNG and comp for placement: 

![open-file](https://user-images.githubusercontent.com/430082/68329452-3d82be00-009f-11ea-9426-2277bdcfa93a.png)

![icons](https://user-images.githubusercontent.com/430082/68329469-46738f80-009f-11ea-8ad6-62509062a695.png)

**Comment by jakeclark** [comment]
"Saved Workspaces" landing page attached. 
![saved-queries](https://user-images.githubusercontent.com/430082/69544748-5d025d80-0f5e-11ea-9a92-97ec5a7e935c.png)

**Comment by cameronmarsh** [comment]
Do the links from the Saved Workspaces page reference the actual visualization links? Since you can have multiple visualizations per dataset

Also, do we want any more information in the links to the visualizations? i.e. the name of the visualization with the dataset or time last saved or something

**Comment by jakeclark** [comment]
The dataset names are placeholders - the actual names would be whatever the user names the visualization workspace as they save it.
