### ISSUE TITLE
Clean up UI Environment Variables

### ISSUE THREAD

**Issue by abrock-accenture** [SmartColumbusOS/discovery_ui#34]
Currently we are setting environment variables on `window` in the discovery_ui app and react_discovery_ui has to know what they are.  These should be passed into the react_discovery_ui component as props.  Additionally, setting these variables on the window is not the recommended way to set environment variables.  Setting any variables on `window` clutters the global namespace.

ACs:
- Variables are no longer set on `window`.
- react_discovery_ui accepts all existing environment variables as props.

Tech Notes:
- Use this recommended approach to pass environment variables into the react app: https://medium.com/@trekinbami/using-environment-variables-in-react-6b0a99d83cf5. Ideally, the run.sh script that we have would go away or be updated to populate a `.env` file containing all of our environment variables.

**Comment by rob-h-m** [comment]
@abrock-accenture Please comment on the value of this, to help us know where to prioritize.  Thanks!

**Comment by rob-h-m** [comment]
@abrock-accenture ^^^ Ping!  Thank you

CC @carriebrinkley
