### ISSUE TITLE
Decrease Webpack Build Time

### ISSUE THREAD

**Issue by LtChae** [SmartColumbusOS/discovery_ui#52]
As a Smartcitiesdata developer, I want my webpack builds to be faster so that I can have quicker feedback cycles for changes.

AC:
- `time npm run build` shows a faster time on average.
- `npm run start` runs fast enough for local development
- Package size is not increased

Tech Notes:
Reasonable build time decided in entry. (Have the 'control' time for the entry)

**Comment by rob-h-m** [comment]
@LtChae Please comment - how much time does it currently take/ what's the expected improvement?  To help with prioritization.  Thanks

**Comment by ManApart** [comment]
I think work Brewer did may have alleviated this issue, but I'm not positive.
