### ISSUE TITLE
Auth0 email confirmation emails should have a From address that is not "discovery"

### ISSUE THREAD

**Issue by jmorris-pillar** [SmartColumbusOS/discovery_ui#89]
Currently when we get a email confirmation..email from auto0 the from: address is "Discovery"

I think this should match smart columbus os branding appropriately.

[ ] Appropriate naming is in the comments
[ ] Update this in auth0 programmatically.

![image.png](https://images.zenhubusercontent.com/5d0a93e4df158845874ae672/c3536b97-f927-40ad-8b3f-8d622442b525)

**Comment by jakeclark** [comment]
This should be "Smart Columbus Operating System," in order to be consistent with our other communications: 

![image.png](https://images.zenhubusercontent.com/5d0b9f3ddf158845874ae8ff/6a69e8d3-c621-475e-94c1-fa9c8cdf7286)
